sudo: false
language: java
#jdk:
#  - openjdk11
before_install:
  - wget https://github.com/TravaOpenJDK/trava-jdk-11-dcevm/releases/download/dcevm-11.0.1%2B8/java11-openjdk-dcevm-linux.tar.gz -O /tmp/jdk.tar.gz
  - cd /tmp
  - tar xf jdk.tar.gz
  - export PATH=/tmp/jdk/bin/:$PATH
  - export JAVA_HOME=/tmp/jdk
  - echo $PATH
  - echo $JAVA_HOME
  - echo 'MAVEN_OPTS="-Xmx2048M -Xss128M -XX:+CMSClassUnloadingEnabled -XX:+TieredCompilation -XX:TieredStopAtLevel=1"' >~/.mavenrc
# default install is mvn install --quiet -DskipTests=true
install: mvn --show-version --quiet clean install -DskipTests
before_script:
  - cd core
script:
  # invoker.streamLogs: we cannot access to log files through Travis web ui, so display everything in the console
  - mvn --show-version verify -Dinvoker.streamLogs=true
after_failure:
  - cat target/log/*
  - cat target/failsafe-reports/org.apache.syncope.fit.*-output.txt
notifications:
  email:
    - ilgrosso@apache.org
