sudo: false
language: java
jdk:
  - openjdk11
before_install:
  - echo 'MAVEN_OPTS="-Xmx2048M -Xss128M -XX:+CMSClassUnloadingEnabled -XX:+TieredCompilation -XX:TieredStopAtLevel=1"' >~/.mavenrc
# default install is mvn install --quiet -DskipTests=true
install: travis_wait 30 mvn --show-version --quiet clean install
before_script:
  - cd core
script:
  # invoker.streamLogs: we cannot access to log files through Travis web ui, so display everything in the console
  - mvn --show-version verify -Dinvoker.streamLogs=true
after_failure:
  - cat target/log/*
  - cat target/failsafe-reports/org.apache.syncope.fit.*-output.txt
notifications:
  email:
    - ilgrosso@apache.org
